### ISSUE TITLE
Example for reading and writing messages in an encrypted room.

### ISSUE THREAD

**Issue by gmosx** [matrix-org/matrix-rust-sdk#135]
I understand that the matrix-sdk supports  end-to-end encryption.

However it's not clear how this could work. A small example showing how to read messages from an encrypted room and how to send messages to an encrypted room would be **extremely helpful**. :pray: 

I have looked at the [cross_signing_bootstrap](https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk/examples/cross_signing_bootstrap.rs) example which sounds related, but I am not sure how to proceed.

**Comment by poljar** [comment]
Encryption will work transparently as long as the `encryption` feature is enabled, if the room the message is being sent to is encrypted the message will be encrypted. Decryption works transparently as well, if a message can be decrypted it will be decrypted.

**Comment by gmosx** [comment]
Hmm, didn't work transparently :( I see this:

![image](https://user-images.githubusercontent.com/37342/107154840-b8f7ad00-697d-11eb-8926-78887abab2e0.png)

**Comment by poljar** [comment]
Well it seems like it did encrypt stuff transparently, though Element didn't receive the key to decrypt the message. Could you take a look at the logs in Element in the developer console, there is likely an error.

What version are you using? If you're on 0.2 could you try master, there might be an error with how the signatures are created on 0.2.

**Comment by gmosx** [comment]
I see errors like this one:

```
Error decrypting event (id=$KOq7-FkhhBuOxoleCCFOBu49PWNk5uQnFTX7RaF-r5I): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: u/fm5I1qc5OhOVTu1q/gbhw+QwUXnIaA+XttaOzN500|BiWRaT9sY/7hV7Urr+8yflEADKPCYg96sl9QGShxfoY]
```

I am using this version:

```toml
[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk.git"
rev = "7b8d2b5319bebcd95eee2c10b1e59641dea46e8e"
default-features = false
features = ["encryption", "rustls-tls", "markdown"]
```

**Comment by poljar** [comment]
No errors before that? The ids there are just hashes and don't leak any info, but they are not important anyways.

Any info how you set up the sync loop?

**Comment by gmosx** [comment]
This is what I tried:

```rust
let homeserver_url = Url::parse(&DEFAULT_HOMESERVER_URL).unwrap();
let username = "username";
let password = "password";

let client_config = ClientConfig::default();
let client = Client::new_with_config(homeserver_url, client_config)?;

let response = client
    .login(username, password, None, Some("Programmatic"))
    .await?;

let user_id = response.user_id;

let response = client.sync_once(SyncSettings::new()).await?;

// if let Err(e) = client.bootstrap_cross_signing(None).await {
//     if let Some(response) = e.uiaa_response() {
//         let auth_data = auth_data(&user_id, &password, response.session.as_deref());
//         let response = client
//             .bootstrap_cross_signing(Some(auth_data))
//             .await
//             .expect("to bootstrap cross signing");
//     } else {
//         panic!("Error during cross signing bootstrap {:#?}", e);
//     }
// }

let room_id = RoomId::try_from(ROOM_ID).unwrap();

client
    .room_send(
        &room_id,
        AnyMessageEventContent::RoomMessage(MessageEventContent::Text(
            TextMessageEventContent::plain("It works!"),
        )),
        None,
    );
```

**Comment by poljar** [comment]
Ah OK, we should indeed document that you need to continuously sync for E2EE to work. So `sync_once()` won't cut it, you'll need to put `sync()` into a background task or use some other method to keep `sync()` alive while doing your message sending.

**Comment by gmosx** [comment]
Thanks for the insight. I am wondering if there is a code snippet somewhere that demonstrates this?

And indeed, it would be great to document this requirement!

**Comment by poljar** [comment]
All of the examples keep a sync running, they either react to events using the [event emitter](https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk/examples/login.rs#L52) or [pass a callback that will be run after every sync successful sync](https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk/examples/emoji_verification.rs#L82).

**Comment by gmosx** [comment]
OK, thanks will study the examples more carefully.

**Comment by gmosx** [comment]
FWIW my use case is to run a single job (e.g. from Cron) to send a specific message to a room (in a fire-and-forget fashion), so both of the above proposals seem a bit weird. But I will give it a try.

**Comment by poljar** [comment]
The client needs to know the members of a room and the devices each member has for E2EE to work, so it needs to keep the state in sync with the server. You can either have a daemon running that listens on a Unix socket for your Cron job or start the client and wait for the sync to finish before sending the the message.

**Comment by gmosx** [comment]
I tried again, still no success:

```rust
use anyhow::Result;
use matrix_sdk::{api::r0::sync::sync_events, identifiers::RoomId, ClientConfig};
use matrix_sdk::{Client, LoopCtrl, SyncSettings};
use std::convert::TryFrom;
use std::time::Duration;
use url::Url;

const DEFAULT_HOMESERVER_URL: &str = "https://matrix.org";
const ROOM_ID: &str = "...";

async fn callback(response: sync_events::Response) -> LoopCtrl {
    let room_id = RoomId::try_from(ROOM_ID).unwrap();
    let room = response.rooms.join.get(&room_id).unwrap();

    for event in &room.timeline.events {
        if let Ok(e) = event.deserialize() {
            println!("---{:?} {:?}", room_id, e);
        }
    }

    LoopCtrl::Continue
}

#[tokio::main]
async fn main() -> Result<()> {
    let homeserver_url = Url::parse(DEFAULT_HOMESERVER_URL).unwrap();

    let client_config = ClientConfig::default();
    let client = Client::new_with_config(homeserver_url, client_config)?;

    let username = "...";
    let password = "...";

    let response = client
        .login(username, password, None, Some("Programmatic"))
        .await?;

    let user_id = response.user_id;
    println!("user_id: {}", user_id);

    let sync_settings = SyncSettings::new().timeout(Duration::from_secs(30));

    client.sync_with_callback(sync_settings, callback).await;

    Ok(())
}
```

**Comment by gmosx** [comment]
Another issue, how can I use the client within the callback? So that I can e.g. send messages to a Room?
Seems like `sync_with_callback` needs `async move || ...` which is an unstable feature?

**Comment by poljar** [comment]
You can clone the `Client` as much as you like and using `|r| async move {}` works on stable.

```rust
client
    .sync_with_callback(sync_settings, |response| async move {
        // Insert your logic here
        LoopCtrl::Continue
    }).await
```

I just noticed that the example for the `sync_with_callback` method hasn't been updated, fixed now.

**Comment by gmosx** [comment]
Thank you!

Using the following 'hack' that I have seem in other examples, I managed to send messages to an encrypted channel:

```rust
    let client_ref = &client;
    client
        .sync_with_callback(sync_settings, |_response| async move {
            let client = &client_ref;
            client.room_send(...)
            ...
```

However, I still cannot read messages from the encrypted channel. Using:

```rust
    ...
    for event in &room.timeline.events {
        if let Ok(e) = event.deserialize() {
            println!("---{:?} {:?}", room_id, e);
        }
    }
```

returns messages like this one:

```
Message(RoomEncrypted(SyncMessageEvent { content: MegolmV1AesSha2(MegolmV1AesSha2Content { ciphertext: "AwgAEoABLnT....Jdi1BruT7w7luq1BM7Am1JG+zTj/EyHWd87JEVaYk4eQsqB0E/vDBwT.....s5QT4HGItwEDAOQ5Y7HduN0DObpSiH39/Ko.....bskHGpJMW7xl1HcDuL3SwHDH69ntvz1kRLgvET6Wevw8kRa8sO2zLwo75TkNGQXYU4xJ187PFFikbvpxuI6IEh0WbrHGu6NTFNpxGuwHZNduL3w5WEEdSQopQg", sender_key: "Eqv...2Uh3zttL0u.....3ulzsIkbi5Kwk", device_id: OERTXMWWN, session_id: "8lO8nqs/2...Kh7Zx55yIaA3c+3PhM", relates_to: None }), event_id: $bf3s1I7AAAAAACZw9NsFDDDE7kY73-xHehi_akq9Aw, sender: @xxxx:matrix.org, origin_server_ts: SystemTime { tv_sec: 1612719356, tv_nsec: 415000000 }, unsigned: Unsigned { age: Some(226612705), transaction_id: None, relations: None } })
```

Am I missing something?

**Comment by poljar** [comment]
It could be that 0.2 creates invalid signatures and thus the device it creates is invalid and doesn't receive E2EE keys, nor do other devices accept them. Could you try master? 

You'll need to remove the `deserialize()` call when switching to master, I think the rest is the same.

**Comment by gmosx** [comment]
Yeah! That did the trick, master works!
Thank you :-D

**Comment by gmosx** [comment]
Actually, it didn't work. I can post messages to an encrypted room, read back my messages, but still cannot read messages from other room participants.

I guess I will just use a non-encrypted room for the moment. Hopefully, there will be some kind of tutorial in the future.

**Comment by poljar** [comment]
If 0.2 created an invalid device you'll have to create a new one, that is nuke your storage for the bot and create it anew.

**Comment by gnunicorn** [comment]
@gmosx is this still an open issue for you? also with latest `main` and the new upgraded encryption setup?

**Comment by bnjbvr** [comment]
No activity after the previous question, so closing as a lot has happened in the meanwhile. Feel free to reopen if there's still an issue!

**Comment by dentropy** [comment]
IDK how there are so many matrix clients when there is no documentation on how to do the encryption and decryption, I get meOLM exists but I can't for the life of me figure out how to use it

**Comment by gmosx** [comment]
Yeap, I never got this to run reliably, though I haven't checked the library for more than a year. I am wondering is there a simple but complete example to demonstrate sending/receiving encrypted messages?

**Comment by bnjbvr** [comment]
> IDK how there are so many matrix clients when there is no documentation on how to do the encryption and decryption, I get meOLM exists but I can't for the life of me figure out how to use it

If you're looking for a high-level explanation, this repo has some for Olm and Megolm: https://gitlab.matrix.org/matrix-org/olm/-/blob/master/docs/olm.md

> Yeap, I never got this to run reliably, though I haven't checked the library for more than a year. I am wondering is there a simple but complete example to demonstrate sending/receiving encrypted messages?

Things have changed a lot over the course of the year, and among other things there's been lots of bugfixes.

The gist of how to do encryption/decryption with the SDK is:

- enable the `encryption` feature
- start `sync()` in the background

You're done. Receiving and sending encrypted messages then happens automatically.

(Admittedly, getting the history of an encrypted room requires cross-device verification, enabling the key backup, and using another client that uses the same key backup implementation.)

**Comment by 3ttercap** [comment]
> > IDK how there are so many matrix clients when there is no documentation on how to do the encryption and decryption, I get meOLM exists but I can't for the life of me figure out how to use it
> 
> If you're looking for a high-level explanation, this repo has some for Olm and Megolm: https://gitlab.matrix.org/matrix-org/olm/-/blob/master/docs/olm.md
> 
> > Yeap, I never got this to run reliably, though I haven't checked the library for more than a year. I am wondering is there a simple but complete example to demonstrate sending/receiving encrypted messages?
> 
> Things have changed a lot over the course of the year, and among other things there's been lots of bugfixes.
> 
> The gist of how to do encryption/decryption with the SDK is:
> 
> * enable the `encryption` feature
> * start `sync()` in the background
> 
> You're done. Receiving and sending encrypted messages then happens automatically.
> 
> (Admittedly, getting the history of an encrypted room requires cross-device verification, enabling the key backup, and using another client that uses the same key backup implementation.)

hi, any updates on this? I'm quite lost with this topic. It seems now there is no feature encryption (in cargo.toml?) to enable and when I use room.send to send a message to an encrypted room, it say  "Olm machine wasn't started"?  :(

**Comment by poljar** [comment]
> hi, any updates on this? I'm quite lost with this topic. It seems now there is no feature encryption (in cargo.toml?) to enable and when I use room.send to send a message to an encrypted room, it say "Olm machine wasn't started"? :(

Care to share your code? It's a bit hard to know what is going wrong without looking at the code.

On the other hand, did you try out any of our examples in the repo? This one should be easy to get going: https://github.com/matrix-org/matrix-rust-sdk/blob/47246483fa43d52ac79b8a6190b27577da5fd906/examples/command_bot/src/main.rs#L69-L79
